// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [
    !SUPABASE_URL && 'VITE_SUPABASE_URL',
    !SUPABASE_PUBLISHABLE_KEY && 'VITE_SUPABASE_PUBLISHABLE_KEY',
  ].filter(Boolean);
  throw new Error(
    `Supabase: variáveis de ambiente faltando no .env: ${missing.join(', ')}. ` +
    'Copie .env.example para .env e preencha com a URL e a chave anon do seu projeto Supabase.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (import.meta.env.DEV) {
  try {
    const url = new URL(SUPABASE_URL);
    // console.info('[Supabase] Projeto conectado:', url.origin, '→ Confira se é o mesmo em Dashboard → Project Settings → API');
  } catch {
    console.warn('[Supabase] URL inválida:', SUPABASE_URL);
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
    },
  },
});